language: cpp

os:
- linux

compiler:
- gcc
- clang

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
  global:
    secure: "0N2Bw0qdLIoX0fW8/SHMobrA6oup/gd5373SwtyA//nP3HVNJpgpnVI8iyZ0ztIlStcWO1tB39XowUFTxT2jGSMM0Xliw501WjIIbaECb6QCkUl1tHJ2NmI7aD36gZcbcAzdTbjab5SJ5yLZR4Barr+zrIQiChu7Ggcg4SIltRs="

before_install:
- echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
- echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
- echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq

install:
- sudo apt-get -qq install build-essential libpng-dev libjpeg-dev
- if [ "$CXX" = "g++" ]; then sudo apt-get -qq --allow-unauthenticated install gcc-4.9 g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ]; then sudo apt-get -qq --allow-unauthenticated install clang-3.6; export CXX="clang++-3.6" CC="clang-3.6"; fi
- wget http://www.ffmpeg.org/releases/ffmpeg-2.6.2.tar.bz2
- tar xf ffmpeg-2.6.2.tar.bz2
- cd ffmpeg-2.6.2 && ./configure --prefix=/usr --disable-static --enable-shared --disable-everything --disable-avdevice --disable-doc --disable-htmlpages --disable-manpages --disable-programs --disable-encoders --disable-muxers --disable-decoders --enable-swscale --disable-yasm --enable-protocol=file --enable-protocol=http --enable-iconv  && make -j4 && sudo make install
- cd ..

script:
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_STATIC=ON -DENABLE_SHARED=ON -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON .
- make -j4
- ls -la /home/travis/build/dirkvdb/ffmpegthumbnailer/test/
- stat /home/travis/build/dirkvdb/ffmpegthumbnailer/test/test_sample.flv
- CTEST_OUTPUT_ON_FAILURE=1 make test

addons:
  coverity_scan:
    project:
      name: "dirkvdb/ffmpegthumbnailer"
      description: "Build submitted via Travis CI"
    notification_email: dirk.vdb@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make -j4"
    branch_pattern: coverity_scan